#!/bin/bash


#realtive path to this script
cd ~/Geometry/Geometry\ Book/

#update output files
mdbook build 

#implement preferences
cd config_files
./add_icons.py
./wrap_sections.py
#./import_styles.py
./import_scripts.py

cp -R css/icons ../book/config_files/css

cd ..
#cd ~Desktop/Geometry\ Book
#rm -rf !(".git")
rm -rf ~Desktop/Geometry\ Book/*
#cd ~/Geometry/Geometry\ Book/

cp -R book/*  ~/Desktop/Geometry\ Book

case $1 in 
	-o | --open)
        
		cd ../book
        firefox index.html #run index.html to view changes
        ;;
esac
